// apps-microservices/crawler-monitor-frontend/src/components/ui/separator.jsx
import * as SeparatorPrimitive from '@radix-ui/react-separator';
import { forwardRef } from 'react';
import { cn } from '../../lib/utils';

const Separator = forwardRef(
  ({ className, orientation = 'horizontal', decorative = true, ...props }, ref) => (
    <SeparatorPrimitive.Root
      ref={ref}
      decorative={decorative}
      orientation={orientation}
      className={cn(
        'shrink-0 bg-border',
        orientation === 'horizontal' ? 'h-[1px] w-full' : 'h-full w-[1px]',
        className
      )}
      {...props}
    />
  )
);
Separator.displayName = SeparatorPrimitive.Root.displayName;

export { Separator };

// apps-microservices/mcp-gateway-frontend/src/components/ui/Separator.vue
<template>
  <Separator
    :decorative="true"
    :orientation="orientation"
    class="shrink-0 bg-gray-200 dark:bg-gray-800"
    :class="orientation === 'horizontal' ? 'h-px w-full' : 'h-full w-px'"
  />
</template>

<script setup lang="ts">
import { Separator } from 'radix-vue'

withDefaults(
  defineProps<{
    orientation?: 'horizontal' | 'vertical'
  }>(),
  { orientation: 'horizontal' },
)
</script>
